name: Build and Product to Alibaba Cloud

on:
  push:
    branches:
      - main # 触发条件：当 main 分支有推送时

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 安装 pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.2.0

      # 3. 设置 Node.js 环境并启用 pnpm 缓存
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' # 根据您的项目需求选择版本
          cache: pnpm

      # 4. 安装依赖
      - name: Install dependencies
        run: pnpm install

      # 5. 构建项目
      - name: Build project
        run: pnpm run build

      # 6. 检查 dist 文件夹是否存在
      - name: Check if .output folder exists
        id: check_output
        run: |
          if [ -d ".output" ]; then
            echo ".output folder exists"
            echo "OUTPUT_EXISTS=true" >> $GITHUB_ENV
          else
            echo ".output folder does not exist"
            echo "OUTPUT_EXISTS=false" >> $GITHUB_ENV
          fi

      # 2. 部署到阿里云服务器
      - name: Deploy to Alibaba Cloud Server
        if: env.OUTPUT_EXISTS == 'true'
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }} # 阿里云服务器 IP 地址
          username: ${{ secrets.SERVER_USER }} # 阿里云服务器用户名（如 root）
          key: ${{ secrets.SSH_PRIVATE_KEY }} # 私钥
          source: '.output/*' # 构建后的文件路径
          target: /var/www/dixiaoping # 阿里云服务器上的目标路径
          script: |
            echo "Files have been uploaded to /var/www/dixiaoping"
            sudo systemctl reload nginx
            echo "Nginx has been reloaded successfully."
